theme: jekyll-theme-slate
title: <a href="https://www.franklin.edu/about-us/faculty-staff/faculty-profiles/whittaker-todd">Todd A. Whittaker</a>, Ph.D.
description: Department Chair, Computing Sciences and Mathematics, Franklin University