theme: jekyll-theme-slate
title: [Todd A. Whittaker](https://www.franklin.edu/about-us/faculty-staff/faculty-profiles/whittaker-todd), Ph.D.
description: Department Chair, [Computing Sciences and Mathematics](https://cs.franklin.edu/), [Franklin University](https://www.franklin.edu/)"